#https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
crds:
  # This option decides if the CRDs should be installed
  # as part of the Helm installation.
  enabled: true