#https://github.com/project-zot/helm-charts/blob/main/charts/zot/values.yaml
service:
  type: ClusterIP
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: "zot1.<example.com>"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  className: "nginx"
  pathtype: ImplementationSpecific
  hosts:
    - host: zot1.<example.com>
      paths:
        - path: /
  tls: 
    - secretName: zot-tls
      hosts:
        - zot1.<example.com>
configFiles:
  config.json: |-
   {
     "storage": { "rootDirectory": "/var/lib/registry" },
     "http": {
       "address": "0.0.0.0",
       "port": "5000",
       "auth": { "htpasswd": { "path": "/secret/htpasswd" } },
       "accessControl": {
         "repositories": {
           "**": {
             "policies": [{
               "users": ["user"],
               "actions": ["read"]
             }],
             "defaultPolicy": []
           }
         },
         "adminPolicy": {
           "users": ["admin"],
           "actions": ["read", "create", "update", "delete"]
         }
       }
     },
     "log": { "level": "debug" }
   }