postgresql_db:
  name: ${BRANCH}-postgresdb
image:
    tag: ${CONTAINER_MAIN_VERSION}-${BRANCH}-${GITHUB_SHA}
    repository: ${OCI_REGISTRY}/${APP_NAME}
ingress:
    enabled: true
    className: "nginx"
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: "${BRANCH}.<example.com>"
    hosts:
        - host: ${BRANCH}.<example.com>
          paths:
            - path: /
              pathType: ImplementationSpecific
    tls: 
        - secretName: ${BRANCH}-app-tls
          hosts:
            - ${BRANCH}.<example.com>
