name: CI-terraform-destroy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Terraform destroy kubernetes-config
        id: fmt-kubernetes
        run: terraform destroy --auto-aprove
        continue-on-error: true
        working-directory: terraform/kubernetes-config

      - name: Terraform destroy kubernetes
        id: fmt-kubernetes
        run: terraform destroy --auto-aprove
        continue-on-error: true
        working-directory: terraform/kubernetes

      - name: Terraform destroy bootstrap
        id: fmt-kubernetes
        run: terraform destroy --auto-aprove
        continue-on-error: true
        working-directory: terraform/bootstrap
        
        
